MGDCTRS-1153 feat: dynamic form improvements
bf2fc6cc711aee1a0c2a/cos-ui pull request #633
Opened 2022-11-07 19:35 UTC by gashcrumb

This change adds a method to start applying some general organization to the schema driven forms.  The kafka topic should be moved to the start of the form, and for AWS based connectors the access key/secret fields are next, followed by the region.  The other change this commit brings in is a new custom control for schema based forms to improve the AWS region selector so that it behaves more like a typeahead control and less like a select control.

![Screenshot from 2022-11-07 14-07-04](https://user-images.githubusercontent.com/351660/200398673-af3a87f5-fa63-479a-8558-9e6cc95b2591.png)

2022-11-07 20:22 UTC, gashcrumb commented
Note, this commit also updates the test fixtures and stories so they're all aligned to the same general root structure.

2022-11-08 07:07 UTC, indraraj requested changes
Nice improvement :+1: @gashcrumb But you may also want to use similar _**organizedProperties**_ object in the "Read mode" of edit flow.
![image](https://user-images.githubusercontent.com/8264372/200497282-8c69277c-bf51-4920-9663-c5b620c7d9dc.png)

2022-11-08 09:57 UTC, uidoyen commented
Nice improvement :+1:

2022-11-08 11:42 UTC, gashcrumb commented
@indraraj Hmm yes, we would probably want to do that  :-)  Good catch!

2022-11-08 12:33 UTC, gashcrumb commented
Ok, here we are, this should cover this case as well for the time being, for example:

![Screenshot from 2022-11-08 07-27-27](https://user-images.githubusercontent.com/351660/200564713-8a8d272d-c437-4c76-b2ff-ca05bea42d0f.png)

2022-11-09 05:57 UTC, indraraj approved these changes

2022-11-09 05:57 UTC, indraraj commented
Tested Locally, looks good :+1:

2022-11-09 05:58 UTC, merged